<a href="https://colab.research.google.com/github/mrzResearchArena/TF-2.X/blob/master/ColabHandle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import sklearn
import torch

In [0]:
print(sklearn.__version__)
print(torch.__version__)

0.21.3
1.3.1


In [0]:
torch.cuda.is_available()

False

In [0]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [0]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243


In [0]:
!uname -a

Linux 5ef38735a71d 4.14.137+ #1 SMP Thu Aug 8 02:47:02 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux


In [0]:
!lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic


In [0]:
!pip install tensorflow-gpu==2.0

     |████████████████████████████████| 380.8MB 76kB/s 
     |████████████████████████████████| 3.8MB 21.2MB/s 
     |████████████████████████████████| 450kB 37.0MB/s 
ERROR: tensorflow 1.15.0rc3 has requirement tensorboard<1.16.0,>=1.15.0, but you'll have tensorboard 2.0.0 which is incompatible.
ERROR: tensorflow 1.15.0rc3 has requirement tensorflow-estimator==1.15.1, but you'll have tensorflow-estimator 2.0.0 which is incompatible.
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1


In [0]:
import tensorflow as tf

In [0]:
tf.__version__

'1.15.0'

# Hi
This is regular test
``` python
for i in range(10):
    print(i)
    
```


In [0]:
!pwd
!lsb_release -a 

/content
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic


In [0]:
!cat /etc/os-release

NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic


In [0]:
!free -h

              total        used        free      shared  buff/cache   available
Mem:            12G        641M        9.9G        848K        2.1G         11G
Swap:            0B          0B          0B


In [0]:
!df -h

Filesystem      Size  Used Avail Use% Mounted on
overlay          49G   28G   19G  60% /
tmpfs            64M     0   64M   0% /dev
tmpfs           6.4G     0  6.4G   0% /sys/fs/cgroup
tmpfs           6.4G  8.0K  6.4G   1% /var/colab
/dev/sda1        55G   29G   27G  53% /etc/hosts
shm             6.0G  4.0K  6.0G   1% /dev/shm
tmpfs           6.4G     0  6.4G   0% /proc/acpi
tmpfs           6.4G     0  6.4G   0% /proc/scsi
tmpfs           6.4G     0  6.4G   0% /sys/firmware


In [0]:
import gym
gym.__version__

'0.15.4'

In [0]:
!pip install --upgrade tensorflow

     |████████████████████████████████| 86.3MB 40kB/s 
     |████████████████████████████████| 450kB 39.6MB/s 
     |████████████████████████████████| 3.8MB 49.7MB/s 
     |████████████████████████████████| 81kB 11.5MB/s 
ERROR: tensorboard 2.0.2 has requirement grpcio>=1.24.3, but you'll have grpcio 1.15.0 which is incompatible.
ERROR: google-colab 1.0.0 has requirement google-auth~=1.4.0, but you'll have google-auth 1.8.2 which is incompatible.
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: google-auth 1.4.2
    Uninstalling google-auth-1.4.2:
      Successfully uninstalled google-auth-1.4.2
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found existing installation: tensorflow 1.15.0
    Uninstalling tensorflow-1.15.0:
      Successfully uninstalle

In [0]:
import tensorflow as tf
tf.__version__

'2.0.0'

In [0]:
!ls

sample_data


In [0]:
!cat sample_data

cat: sample_data: Is a directory


In [0]:
!cd sample_data

In [0]:
!pwd

/content


In [0]:
!ls

sample_data


In [0]:
!ls sample_data

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


In [0]:
!ls

sample_data


In [0]:
!ls -l

total 4
drwxr-xr-x 1 root root 4096 Dec 12 16:48 sample_data


In [0]:
!pwd

/content


In [0]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

--2019-12-16 02:24:16--  https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4551 (4.4K) [application/x-httpd-php]
Saving to: ‘iris.data’

iris.data           100%[===================>]   4.44K  --.-KB/s    in 0s      

2019-12-16 02:24:17 (106 MB/s) - ‘iris.data’ saved [4551/4551]



In [0]:
!ls

iris.data  sample_data


In [0]:
!head iris.data

5.1,3.5,1.4,0.2,Iris-setosa
4.9,3.0,1.4,0.2,Iris-setosa
4.7,3.2,1.3,0.2,Iris-setosa
4.6,3.1,1.5,0.2,Iris-setosa
5.0,3.6,1.4,0.2,Iris-setosa
5.4,3.9,1.7,0.4,Iris-setosa
4.6,3.4,1.4,0.3,Iris-setosa
5.0,3.4,1.5,0.2,Iris-setosa
4.4,2.9,1.4,0.2,Iris-setosa
4.9,3.1,1.5,0.1,Iris-setosa


In [0]:
!ls /home

In [0]:
from google.colab import files
files.upload()

Saving pima.csv to pima.csv


{'pima.csv': b'6,148,72,35,0,33.6,0.627,50,1\n1,85,66,29,0,26.6,0.351,31,0\n8,183,64,0,0,23.3,0.672,32,1\n1,89,66,23,94,28.1,0.167,21,0\n0,137,40,35,168,43.1,2.288,33,1\n5,116,74,0,0,25.6,0.201,30,0\n3,78,50,32,88,31.0,0.248,26,1\n10,115,0,0,0,35.3,0.134,29,0\n2,197,70,45,543,30.5,0.158,53,1\n8,125,96,0,0,0.0,0.232,54,1\n4,110,92,0,0,37.6,0.191,30,0\n10,168,74,0,0,38.0,0.537,34,1\n10,139,80,0,0,27.1,1.441,57,0\n1,189,60,23,846,30.1,0.398,59,1\n5,166,72,19,175,25.8,0.587,51,1\n7,100,0,0,0,30.0,0.484,32,1\n0,118,84,47,230,45.8,0.551,31,1\n7,107,74,0,0,29.6,0.254,31,1\n1,103,30,38,83,43.3,0.183,33,0\n1,115,70,30,96,34.6,0.529,32,1\n3,126,88,41,235,39.3,0.704,27,0\n8,99,84,0,0,35.4,0.388,50,0\n7,196,90,0,0,39.8,0.451,41,1\n9,119,80,35,0,29.0,0.263,29,1\n11,143,94,33,146,36.6,0.254,51,1\n10,125,70,26,115,31.1,0.205,41,1\n7,147,76,0,0,39.4,0.257,43,1\n1,97,66,15,140,23.2,0.487,22,0\n13,145,82,19,110,22.2,0.245,57,0\n5,117,92,0,0,34.1,0.337,38,0\n5,109,75,26,0,36.0,0.546,60,0\n3,158,76,36,245

In [0]:
!ls

iris.data  pima.csv  sample_data


In [0]:
import pandas as pd
D = pd.read_csv('pima.csv', header=None)

In [0]:
D

0    1   2   3    4     5      6   7  8
0     6  148  72  35    0  33.6  0.627  50  1
1     1   85  66  29    0  26.6  0.351  31  0
2     8  183  64   0    0  23.3  0.672  32  1
3     1   89  66  23   94  28.1  0.167  21  0
4     0  137  40  35  168  43.1  2.288  33  1
..   ..  ...  ..  ..  ...   ...    ...  .. ..
763  10  101  76  48  180  32.9  0.171  63  0
764   2  122  70  27    0  36.8  0.340  27  0
765   5  121  72  23  112  26.2  0.245  30  0
766   1  126  60   0    0  30.1  0.349  47  1
767   1   93  70  31    0  30.4  0.315  23  0

[768 rows x 9 columns]

In [0]:
from google.colab import files
files.upload()

Saving dxf.py to dxf.py


{'dxf.py': b'def dx(x, alpha):\n\tfor i in range(1, 10):\n\t\tdx = (2*x) - 6\n\t\tx = x - (alpha * dx)\n\n\t\t# print(dx, xNext, x)\n\n\t#end for\n\treturn x\n\n\n# def f(x):\n#     return (x**2) - (6*x) + 5\n#\n# import numpy as np\n# v = np.array(range(-5, 10))\n#\n# print(f(v))\n'}

In [0]:
from dxf import dx

ModuleNotFoundError: ignored

In [0]:
dx(10, 0.01)

8.836234334911047

## Accessing from Google Drive

In [0]:
!ls /content/gdrive

ls: cannot access '/content/gdrive': No such file or directory


In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
!pwd

/content


In [0]:
!ls

gdrive	sample_data


In [0]:
!ls gdrive/

'My Drive'


In [0]:
!ls /content/gdrive/My\ Drive

 011-141-144.gdoc
'1 intro.pptx'
 5d242a18d36f5614.pdf
 Abril2014.arff
'account page.pdf'
 ACP-DL.gdoc
 ACT_111.pdf
 American_English.gdoc
'Andreas Müller-Introduction to Machine Learning with Python A Guide for Data Scientists.pdf'
 AntiCancerPeptides.gdoc
'Attendee 6 (Rafsanjani Muhammod)'
 Backup
 backup-TUD.gdoc
'bacteriophage proteins.gdoc'
'Badda Home Calculation:.gdoc'
 bangla_digits
'Baysian AI.gdoc'
 b.csv
 b.csv.gsheet
'Big Data with Python-1.gslides'
'Big Data with Python-2.gslides'
'Big Data with Python-3.gslides'
'Big Data with Python-4.gslides'
'bioinformatics ( CSE 493 )'
'Bioinformatics Current Research Topics.gdoc'
'Bioinformatics Dictionary.gdoc'
'Bioinformatics Papers Writing Techniques with Toha.gdoc'
 BioTool.gdoc
 Bk.zip
 BlackLists.gdoc
'Body Lotion.gslides'
'Book report (1).gdoc'
'Book report.gdoc'
'BSc_Official_Transcript (1).pdf'
 BSc_Official_Transcript.pdf
 ClassLectures
 Code.gsheet
'Colab Notebooks'
 ColorManuscript.zip
'Comparing!.gdoc'
 Copy.gdoc
'Copy 

In [0]:
import pandas as pd
data = pd.read_csv('/content/gdrive/My Drive/pima.csv')

In [0]:
data

5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

# Matrix Multiplication
### inner product, outer product, dot product, element-wesed product

In [0]:
import numpy as np
a = np.array([[1,2], [3,4]])
b = np.array([[11, 12], [13, 14]])

In [0]:
a * b

array([[11, 24],
       [39, 56]])

In [0]:
np.dot(a, b)

array([[37, 40],
       [85, 92]])

In [0]:
a @ b

array([[37, 40],
       [85, 92]])

In [0]:
np.inner(a, b)

array([[35, 41],
       [81, 95]])

In [0]:
np.outer(a, b)

array([[11, 12, 13, 14],
       [22, 24, 26, 28],
       [33, 36, 39, 42],
       [44, 48, 52, 56]])